#!/usr/bin/env bash

export REPROJECT_OUTPUT_ROOT="/Users/admin/Documents/LAB/SALIENCY_code/#meshes_2.0/GITHUB/Mesh-Saliency-Projection/test/output_local"
export REPROJECT_REPO_ROOT="/Users/admin/Documents/LAB/SALIENCY_code/#meshes_2.0/GITHUB/Mesh-Saliency-Projection"
export REPROJECT_CANONICAL_JSON_ROOT="${REPROJECT_REPO_ROOT}/jsons/object_placement"

export REPROJECT_DATASET_3DVA_ROOT="/Users/admin/Documents/LAB/Dataset/3DVA"
export REPROJECT_DATASET_MESHMAMBA_ROOT="/Users/admin/Documents/LAB/SALIENCY_code/GAZE_DATA/datasets/MeshMamba/MeshMambaSaliency"
export REPROJECT_DATASET_SAL3D_ROOT="/Users/admin/Documents/LAB/SALIENCY_code/GAZE_DATA/datasets/SAL3D/SAL3D_Dataset"

export REPROJECT_GAZE_CSV_3DVA_ROOT="/Users/admin/Documents/LAB/SALIENCY_code/GAZE_DATA/csv_for_models/3DVA"
export THREE_DVA_CSV_ROOT="${REPROJECT_GAZE_CSV_3DVA_ROOT}"
export REPROJECT_GAZE_JSON_3DVA_ROOT="${REPROJECT_CANONICAL_JSON_ROOT}/3dva_jsons"
export THREE_DVA_JSON_ROOT="${REPROJECT_GAZE_JSON_3DVA_ROOT}"

export REPROJECT_GAZE_CSV_MESHMAMBA_NON_TEXTURE_ROOT="/Users/admin/Documents/LAB/SALIENCY_code/GAZE_DATA/csv_for_models/MeshMamba_non_texture"
export MESHMAMBA_CSV_ROOT="${REPROJECT_GAZE_CSV_MESHMAMBA_NON_TEXTURE_ROOT}"
export REPROJECT_GAZE_JSON_MESHMAMBA_NON_TEXTURE_ROOT="${REPROJECT_CANONICAL_JSON_ROOT}/mamba_non_jsons"
export MESHMAMBA_JSON_ROOT="${REPROJECT_GAZE_JSON_MESHMAMBA_NON_TEXTURE_ROOT}"

export REPROJECT_GAZE_CSV_MESHMAMBA_RGB_TEXTURE_ROOT="/Users/admin/Documents/LAB/SALIENCY_code/GAZE_DATA/csv_for_models/MeshMamba_rgb_texture"
export MESHMAMBA_RGB_TEXTURE_CSV_ROOT="${REPROJECT_GAZE_CSV_MESHMAMBA_RGB_TEXTURE_ROOT}"
export REPROJECT_GAZE_JSON_MESHMAMBA_RGB_TEXTURE_ROOT="${REPROJECT_CANONICAL_JSON_ROOT}/mamba_rgb_jsons"
export MESHMAMBA_RGB_TEXTURE_JSON_ROOT="${REPROJECT_GAZE_JSON_MESHMAMBA_RGB_TEXTURE_ROOT}"

export REPROJECT_GAZE_CSV_SAL3D_ROOT="/Users/admin/Documents/LAB/SALIENCY_code/GAZE_DATA/csv_for_models/SAL3D"
export SAL3D_CSV_ROOT="${REPROJECT_GAZE_CSV_SAL3D_ROOT}"
export REPROJECT_GAZE_JSON_SAL3D_ROOT="${REPROJECT_CANONICAL_JSON_ROOT}/sal3d_jsons"
export SAL3D_JSON_ROOT="${REPROJECT_GAZE_JSON_SAL3D_ROOT}"
export REPROJECT_SAL3D_SMOOTH_GAZE_ROOT="${REPROJECT_DATASET_SAL3D_ROOT}/Smooth_Gaze"

export REPROJECT_VIDEO_3DVA_ROOT="/Users/admin/Documents/LAB/SALIENCY_code/videos/3DVA"
export REPROJECT_VIDEO_MESHMAMBA_NON_TEXTURE_ROOT="/Users/admin/Documents/LAB/SALIENCY_code/videos/MeshMamba_non_texture"
export REPROJECT_VIDEO_MESHMAMBA_RGB_TEXTURE_ROOT="/Users/admin/Documents/LAB/SALIENCY_code/videos/MeshMamba_rgb_texture"
export REPROJECT_VIDEO_SAL3D_ROOT="/Users/admin/Documents/LAB/SALIENCY_code/videos/SAL3D"
