#!/usr/bin/env bash

export REPROJECT_WORK_ROOT="/home/29d_kon@lab.graphicon.ru/ssd1_link/projects/REPROJECTING"
export REPROJECT_OUTPUT_ROOT="$REPROJECT_WORK_ROOT/outputs"
export REPROJECT_REPO_ROOT="$REPROJECT_WORK_ROOT/Mesh-Saliency-Projection"
export REPROJECT_CANONICAL_JSON_ROOT="$REPROJECT_REPO_ROOT/jsons/object_placement"

export REPROJECT_DATASET_3DVA_ROOT="/home/29d_kon@lab.graphicon.ru/ssd1_link/datasets/3DVA"
export REPROJECT_DATASET_MESHMAMBA_ROOT="/home/29d_kon@lab.graphicon.ru/ssd1_link/datasets/MeshMambaSaliency"
export REPROJECT_DATASET_SAL3D_ROOT="/home/29d_kon@lab.graphicon.ru/ssd1_link/datasets/reproject_release_v1/SAL3D"

export REPROJECT_GAZE_CSV_3DVA_ROOT="$REPROJECT_WORK_ROOT/side_inputs/3DVA/csv"
export THREE_DVA_CSV_ROOT="$REPROJECT_GAZE_CSV_3DVA_ROOT"
export REPROJECT_GAZE_JSON_3DVA_ROOT="$REPROJECT_CANONICAL_JSON_ROOT/3dva_jsons"
export THREE_DVA_JSON_ROOT="$REPROJECT_GAZE_JSON_3DVA_ROOT"

export REPROJECT_GAZE_CSV_MESHMAMBA_NON_TEXTURE_ROOT="$REPROJECT_WORK_ROOT/side_inputs/MeshMamba_non_texture/csv"
export MESHMAMBA_CSV_ROOT="$REPROJECT_GAZE_CSV_MESHMAMBA_NON_TEXTURE_ROOT"
export REPROJECT_GAZE_JSON_MESHMAMBA_NON_TEXTURE_ROOT="$REPROJECT_CANONICAL_JSON_ROOT/mamba_non_jsons"
export MESHMAMBA_JSON_ROOT="$REPROJECT_GAZE_JSON_MESHMAMBA_NON_TEXTURE_ROOT"

export REPROJECT_GAZE_CSV_MESHMAMBA_RGB_TEXTURE_ROOT="$REPROJECT_WORK_ROOT/side_inputs/MeshMamba_rgb_texture/csv"
export MESHMAMBA_RGB_TEXTURE_CSV_ROOT="$REPROJECT_GAZE_CSV_MESHMAMBA_RGB_TEXTURE_ROOT"
export REPROJECT_GAZE_JSON_MESHMAMBA_RGB_TEXTURE_ROOT="$REPROJECT_CANONICAL_JSON_ROOT/mamba_rgb_jsons"
export MESHMAMBA_RGB_TEXTURE_JSON_ROOT="$REPROJECT_GAZE_JSON_MESHMAMBA_RGB_TEXTURE_ROOT"

export REPROJECT_GAZE_CSV_SAL3D_ROOT="/home/29d_kon@lab.graphicon.ru/ssd1_link/datasets/reproject_release_v1/gaze_csv/SAL3D"
export SAL3D_CSV_ROOT="$REPROJECT_GAZE_CSV_SAL3D_ROOT"
export REPROJECT_GAZE_JSON_SAL3D_ROOT="$REPROJECT_CANONICAL_JSON_ROOT/sal3d_jsons"
export SAL3D_JSON_ROOT="$REPROJECT_GAZE_JSON_SAL3D_ROOT"
export REPROJECT_SAL3D_SMOOTH_GAZE_ROOT="$REPROJECT_DATASET_SAL3D_ROOT/Smooth_Gaze"
